name: talamiz_arina
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  animate_do: ^4.2.0
  animated_theme_switcher: ^2.0.10
  buttons_tabbar: ^1.3.15
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  custom_sliding_segmented_control: ^1.8.5
  dart_either: ^2.0.0
  date_picker_timeline: ^1.2.7
  dio: ^5.9.0
  dotted_border: ^3.1.0
  dotted_line: ^3.2.3
  dropdown_button2: ^2.3.9
  dynamic_height_list_view: ^0.0.2
  expandable_page_view: ^1.0.17
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_blurhash: ^0.9.1
  flutter_localizations:
    sdk: flutter
  flutter_pretty_dio_logger: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.2
  gap: ^3.0.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  image: ^4.5.4
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  injectable: null
  intl: any
  json_annotation: null
  logger: ^2.6.0
  lottie: ^3.3.2
  msal_auth: ^3.3.0
  overlapping_avatar: ^1.0.2
  phone_numbers_parser: ^9.0.3
  pinput: ^5.0.2
  retrofit: null
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  step_progress: ^2.7.1
  video_player: ^2.10.1
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  build_runner: null

  flutter_lints: null
  flutter_test:
    sdk: flutter
  injectable_generator: null
  json_serializable: null
  retrofit_generator: null

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/gif/
    - assets/images/lottie/

  fonts:

    - family: SF-Pro-Rounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Black.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Rounded-Heavy.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf
          weight: 100
    - family: sf-arabic-rounded
      fonts:
        - asset: assets/fonts/sf-arabic-rounded.ttf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/helper/
  filename: assets_helper.dart

# flutter_intl:
#   enabled: true
